[package]
name = "aurora-launchpad-tests-alt-token"
description = "NEP-141 token used in tests for Launchpad contract"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "5"
near-contract-standards = "5"
