name: Tests
on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  formatting:
    name: Code Formatting
    runs-on: k8s-worker-4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
      - run: cargo make fmt

  linter:
    name: Code Linter
    runs-on: k8s-worker-4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
      - name: Run cargo clippy
        run: cargo make clippy

  tests:
    name: Tests
    runs-on: k8s-worker-6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
      - name: Run cargo test
        run: cargo make test
